// Code generated by Wire. DO NOT EDIT.
//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"

	"github.com/agnivo/agnivo/packages/platform/config"
)

// initCore assembles Core from configuration following the ProviderSet graph.
func initCore(ctx context.Context, cfg *config.Config) (*Core, error) {
	zapLogger, err := provideLogger(cfg)
	if err != nil {
		return nil, err
	}
	registry := provideMetrics(cfg)
	provider, err := provideTracing(ctx, cfg)
	if err != nil {
		return nil, err
	}
	db, err := providePostgres(ctx, cfg, zapLogger, registry)
	if err != nil {
		return nil, err
	}
	client, err := provideRedis(ctx, cfg, zapLogger, registry)
	if err != nil {
		return nil, err
	}
	healthRegistry := provideHealth()
	core := &Core{
		Logger:  zapLogger,
		Metrics: registry,
		Tracer:  provider,
		DB:      db,
		Redis:   client,
		Health:  healthRegistry,
	}
	return core, nil
}
